name: .NET Build & Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # or 7.0.x/6.0.x if your project requires it

    - name: Restore NuGet packages
      run: dotnet restore ./src/TABFRET.csproj

    - name: Build in Release mode
      run: dotnet build ./src/TABFRET.csproj --configuration Release --no-restore

    - name: Run tests (if you have tests)
      run: dotnet test ./tests/YourTestProject.csproj --no-build --configuration Release
      continue-on-error: true
      if: exists('tests/YourTestProject.csproj')

    - name: Publish artifacts (optional)
      if: success()
      run: dotnet publish ./src/TABFRET.csproj --configuration Release --output ./publish --no-restore --no-build

    - name: Upload build artifacts (optional)
      uses: actions/upload-artifact@v4
      with:
        name: TABFRET
        path: ./publish
      if: success()
