name: .NET Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'
      - name: Restore dependencies
        run: dotnet restore ./src/TABFRET.csproj
      - name: Build
        run: dotnet build ./src/TABFRET.csproj --no-restore --configuration Release
      - name: Test
        run: dotnet test ./src/TABFRET.csproj --no-build --verbosity normal
