name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore TABFRET.sln

    - name: Build solution
      run: dotnet build TABFRET.sln --configuration Release --no-restore

    - name: Run tests
      run: dotnet test TABFRET.sln --configuration Release --no-build --verbosity normal

    - name: Publish application
      run: dotnet publish ./src/TABFRET.csproj --configuration Release --output ./publish --no-build

    - name: Create release package
      run: |
        cd publish
        Compress-Archive -Path * -DestinationPath ../TABFRET-${{ github.ref_name }}.zip

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: TABFRET-${{ github.ref_name }}.zip
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
